
# Default Domain Controler from Vagrant file
# You need to Update it also if you need to change the IP in Vagrant file
# to Provision the Domain, or add more Hosts

all:
  hosts:
    dc1:
      ansible_host: dc1.dev.local
      ansible_port: 5985
    win2016s1:
      ansible_host: 10.233.15.61
    w2012r2s1:
      ansible_host: 10.233.15.62

windows:
  hosts:
    dc1:
    win2016s1:
    win202r2s1:
  vars:
    ansible_user: "vagrant"
    ansible_password: "vagrant"
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_kerberos_delegation: true