
- name: "Executing join-domain.yml"
  gather_facts: false
  hosts: w2016s1
  tasks:
    - name: Joining Development Domain
      win_domain_membership:
        dns_domain_name: dev.local
        domain_admin_user: 'vagrant@dev.local'
        domain_admin_password: 'vagrant'
        state: domain
      register: domain_join_result
    
    # Don't know why but sometimes it joines, and return with 500 error and not rebooting,
    # a rerun also stated that a reboot is not required, but system domainjoined and a reboot is required
    
    - name: "Reboot if required"
      when: domain_join_result.reboot_required
      win_reboot:
        shutdown_timeout: 3600
        reboot_timeout: 3600


